# Generated by Django 5.1.4 on 2024-12-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=40)),
                ('to_place', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('pin', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bus_no', models.BigIntegerField()),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('certificate', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=50)),
                ('OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('role', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.login')),
                ('OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.owner')),
                ('busname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=40)),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.route')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=50)),
                ('starttime', models.CharField(max_length=50)),
                ('endtime', models.CharField(max_length=50)),
                ('tripname', models.CharField(max_length=50)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.bus')),
                ('routename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.route')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.bus')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.user')),
            ],
        ),
    ]
