# Generated by Django 5.1.4 on 2025-01-16 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0002_remove_user_image_remove_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bustrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoptime', models.CharField(max_length=50)),
                ('TIME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.time')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.stop')),
            ],
        ),
    ]
