# Generated by Django 5.1.4 on 2025-02-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0003_bustrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='BUS',
        ),
    ]
