# Generated by Django 5.1.4 on 2025-02-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0004_remove_feedback_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(),
        ),
    ]
