# Generated by Django 5.1.4 on 2025-02-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0006_busstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('count', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
    ]
