# Generated by Django 5.1.4 on 2025-02-21 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0007_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='My_App.staff'),
            preserve_default=False,
        ),
    ]
