# Generated by Django 5.1.4 on 2025-03-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0009_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('STOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.stop')),
            ],
        ),
    ]
