# Generated by Django 5.1.4 on 2025-04-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0010_newlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
